services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: boutique
      POSTGRES_USER: boutique
      POSTGRES_PASSWORD: boutique
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/fathani1207/boutique-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=boutique
      - DATABASE_USER=boutique
      - DATABASE_PASSWORD=boutique
    depends_on:
      - db

  frontend:
    image: ghcr.io/fathani1207/boutique-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres-data:
